### ISSUE TITLE
typedef, namespace support

### ISSUE THREAD

**Issue by westito** [BreX900/data_class#1]
Generator not respects namespaces nor aliases. The latter is not so important, but missing namespace support causes compile error. 

```dart
import 'package:some_package/api.dart' as api;

typedef MyCustomDate = DateTime

@DataClass()
class Product with _$Product {
    final api.Product apiProduct;
    final MyCustomDate date;
}
```
generates:
```dart
  Product copyWith({
    Product? apiProduct,
    DateTime? date,
  }) 
```

**Comment by SimoneBressan** [comment]
I added typealias support and an example in version 0.3.0.
As for the imports with the prefix, they are not supported by `json_serializable` either and the implementation is complicated. PR or suggestions are always welcome

**Comment by BreX900** [comment]
I added typealias support and an example in version 0.3.0.
As for the imports with the prefix, they are not supported by json_serializable either and the implementation is complicated. PR or suggestions are always welcome

**Comment by westito** [comment]
Solution for a similar problem. 
https://github.com/dart-lang/sdk/commit/208d65324abfb74370b02b6bb511b63a56111a51

**Comment by BreX900** [comment]
Support has been added for library versions 1.0.0. 
Thanks so much for your patience
