### ISSUE TITLE
Suggestion: Optimize generated code

### ISSUE THREAD

**Issue by ykrasik** [BreX900/data_class#12]
Hi again,

I wanted to bring up a suggestion that this library could generate code that is more optimized. Currently it relies on iterating over props, which is slower than "hand written" equals or hashcode. It's not "slow" because it takes probably micro or nanoseconds, but its relatively slower than what you would write manually. Here's a sample benchmark:

`test.dart`

```dart
import 'package:mek_data_class/mek_data_class.dart';

part 'gen/test.g.dart';

@DataClass()
class TestDataClass with _$TestDataClass {
  final String name;
  final int age;
  TestDataClass(this.name, this.age);
}

class TestManualClass {
  final String name;
  final int age;
  TestManualClass(this.name, this.age);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TestManualClass &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          age == other.age;

  @override
  int get hashCode => name.hashCode ^ age.hashCode;
}

const warmupIterations = 10000;
const iterations = 10000000;

void main() {
  test('TestManualClass', TestManualClass('John', 30), TestManualClass('Jack', 31));
  test('TestDataClass', TestDataClass('John', 30), TestDataClass('Jack', 31));
}

void test(String name, Object a, Object b) {
  for (var i = 0; i < warmupIterations; i++) {
    a == b;
  }

  final stopwatch = Stopwatch()..start();
  for (var i = 0; i < iterations; i++) {
    a == b;
  }
  stopwatch.stop();
  print("$name equals: ${stopwatch.elapsedMilliseconds}");

  stopwatch.reset();

  for (var i = 0; i < warmupIterations; i++) {
    a.hashCode;
  }

  stopwatch.start();
  for (var i = 0; i < iterations; i++) {
    a.hashCode;
  }
  stopwatch.stop();
  print("$name hashCode: ${stopwatch.elapsedMilliseconds}");
}
```

On my machine, i9 9900K, I get the following:
```
TestManualClass equals: 65
TestManualClass hashCode: 48
TestDataClass equals: 1061
TestDataClass hashCode: 751
```

It also may have a slight impact on garbage collection as it needs to allocate iterators, but I didn't measure that.

So seeing as this is a codegen lib, I think this is exactly what a codegen lib should do - generate the boring boilerplate. I understand why it currently generates what it does - it's a simpler implementation. But since it already has access to all the fields, it can generate something that resembles the "manual" version more.

Curious about your thoughts on this. And thanks for this lib regardless :)

**Comment by BreX900** [comment]
@ykrasik Thanks so much for the feedback.

The current implementation was done this way to support deep equality with`DeepCollectionEquality` of [collection](https://pub.dev/packages/collection) package.

You could let the developer decide whether to use shallow equality or deep equality.
- **shallow equality**: implement the methods as you wrote them, then compare field by field
- **deep equality**: we can use the `Equality` classes only for `Set`, `Map`, `List`, `Iterable` for the rest of the fields it behaves like the shallow equality.

Maybe it's better to "not support" `Iterable` in deep equality with `IterableEquality` so that if you use packages like `built_collection` or `fast_immutable_collections` they use their comparison methods and hashcode for lists and sets

For those using the package, *deep equality* will be active by default so as not to break anything

What do you think?


So you might have something like this based on your setup:
```dart
class DataClass {
  static const Equality<List<Object?>?> $list = ListEquality(DeepCollectionEquality());
  static const Equality<Set<Object?>?> $set = SetEquality(DeepCollectionEquality());
  static const Equality<Map<Object?, Object?>?> $map =
      MapEquality(keys: DeepCollectionEquality(), values: DeepCollectionEquality());

  static int $jc(int hash, int value) {
    hash = 0x1fffffff & (hash + value);
    hash = 0x1fffffff & (hash + ((0x0007ffff & hash) << 10));
    return hash ^ (hash >> 6);
  }

  static int $jf(int hash) {
    hash = 0x1fffffff & (hash + ((0x03ffffff & hash) << 3));
    hash = hash ^ (hash >> 11);
    return 0x1fffffff & (hash + ((0x00003fff & hash) << 15));
  }
}
```
```dart
class ClassWithDeepEquality {
  final bool isBool;
  final List<Object?> maybeList;

  ClassWithDeepEquality(this.isBool, this.maybeList);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassWithDeepEquality &&
          runtimeType == other.runtimeType &&
          isBool == other.isBool &&
          DataClass.$list.equals(maybeList, other.maybeList);

  @override
  int get hashCode {
    var hashCode = 0;
    hashCode = DataClass.$jc(hashCode, isBool.hashCode);
    hashCode = DataClass.$jc(hashCode, DataClass.$list.hash(maybeList));
    return DataClass.$jf(hashCode);
  }
}
```

```dart
class ClassWithShallowEquality {
  final bool isBool;
  final BuiltList<Object?> maybeList;

  ClassWithShallowEquality(this.isBool, this.maybeList);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClassWithShallowEquality &&
          runtimeType == other.runtimeType &&
          isBool == other.isBool &&
          maybeList == other.maybeList;

  @override
  int get hashCode {
    var hashCode = 0;
    hashCode = DataClass.$jc(hashCode, isBool.hashCode);
    hashCode = DataClass.$jc(hashCode, maybeList.hashCode);
    return DataClass.$jf(hashCode);
  }
}
```

**Comment by ykrasik** [comment]
Hi @BreX900 ,

I also think that DeepEquality is the better default and should stay like that. I don't think shallow equality really makes sense for a data class, because a data class should be compared by the equality of its values, not by reference. It can cause unexpected scenarios where 2 data classes contain the exact same values & elements, but are not considered equal because one of its fields which is a collection isn't identical. And if its for optimization - deep equality first check for referential identity.

I think the example you posted with the generated code for `ClassWithDeepEquality` is pretty much what I had in mind. The generated equals uses each field's native equality and delegates to a specific collection equality for collection types. I think having this library do that would be awesome!

**Comment by BreX900** [comment]
@ykrasik Released a new version with this improvement. 
If there are no problems or other suggestions, close the issue
A thousand thanks

**Comment by ykrasik** [comment]
This is awesome, ran some basic use-cases through this and it works great. Thanks a lot for this! I feel like this is a much required but missing native functionality from Dart, so I hope this library catches on :)
