### ISSUE TITLE
Suggestion: add simple serialization methods

### ISSUE THREAD

**Issue by JCKodel** [BreX900/data_class#18]
It would be nice if we could serialize and deserialize those classes to a `Map<String, Object>`.

Nothing fancy, only drop the values inside the map and vice-versa. No conversions, no renaming, nothing.

So,

```dart
@DataClass()
class Product with _$Product {
  final String title;
  @DataField(equality: DefaultEquality())
  final double price;

  const Product({
    required this.title,
    required this.price,
  });
  
  String get titlePrice => '$title$price';
}
```

outputs 

```dart
// This is a Map, not a JSON string!
<String, Object>{
  "title": "some title",
  "price": 3.14,
}
```

And that's it! The dev would be responsible to make this map encodable by, let's say, JSON (then, there, it will handle incompatible types, such as `DateTime`, `Enum`, etc.)

**Comment by SimoneBressan** [comment]
You can use the [json_serializable](https://pub.dev/packages/json_serializable) package
It is outside the purview of this package

**Comment by JCKodel** [comment]
Nevermind, https://pub.dev/packages/dart_mappable already does that.
