### ISSUE TITLE
DataField annotation not respects updatable option

### ISSUE THREAD

**Issue by westito** [BreX900/data_class#2]
When I set `updatable: false` to a field it is still generated into the data class. As I see in generator code this check is missing.
<img width="332" alt="Képernyőfotó 2022-12-22 - 16 04 34" src="https://user-images.githubusercontent.com/536799/209162915-63ebfb90-1e80-45e8-b5ba-de2e37530630.png">
<img width="659" alt="Képernyőfotó 2022-12-22 - 16 02 56" src="https://user-images.githubusercontent.com/536799/209162599-8876a9ce-8e3d-4b85-8ce4-581cc7ec74f2.png">

**Comment by BreX900** [comment]
Thank you so much for reporting!

My intention for updatable was to disable the ability to update the field.
Your problem is that I'm trying to update a field that doesn't exist on the constructor. To fix your problem I'll do as json_serializable, check if there are getters for the fields and passed to the constructor

Thanks!

**Comment by westito** [comment]
As the comment says `It will be considered in the copyWith and/or change methods`. That's why I expected the exclusion from copyWith. I set these fields in the constructor for pre-caching purpose:

<img width="583" alt="Képernyőfotó 2022-12-22 - 16 53 11" src="https://user-images.githubusercontent.com/536799/209172274-10bf022a-aa06-44ac-a709-968029a32583.png">

**Comment by SimoneBressan** [comment]
@westito I released version 0.4.0 of the generator where I fix this bug.
You shouldn't need `@DataField(updatable: false)` unless you don't want to block changes for that value.

**Comment by westito** [comment]
Thanks! `updatable` option works now, but ToString went broken :) As I see the fields are populated from constructor. This is not good because I have fields that's not listen in constructor however I want to see in ToString list.

**Comment by BreX900** [comment]
In version 1.0.0 you can set in build.yaml the possibility to include all the fields of a class instead of using only those of the constructor for the toString method. 
```yaml
mek_data_class_generator:data_class:
  options:
    params | fields
```
