### ISSUE TITLE
Make *Changes class public

### ISSUE THREAD

**Issue by Nico04** [BreX900/data_class#30]
A bit like the Builder, I often need to store the Changes class in a field of the bloc class, so I need to declare the type. Unfortunately the Change class is currently private, making that impossible.
Can you make the Change class public so it can be used in the bloc ?
Thanks.

**Comment by SimoneBressan** [comment]
@Nico04 You can make `*Changes` classes public by setting in `DataClass(changesVisible: true)` annotation or you can change it directly from the build runner options https://pub.dev/packages/mek_data_class#global-configs

**Comment by Nico04** [comment]
Woua that's perfect indeed.
Don't know how I missed it, sorry.
Thanks for your quick answer !
